name: Notify Workflow Dev Push

on:
  workflow_dispatch:
  push:
    branches: [main]   # atau branch kamu
    paths-ignore:
     - README.md
     - .github/*.md
    
jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id="$TELEGRAM_CHANNEL_ID" \
          --data-urlencode "text=🚀 Workflow repo update!
           
           📦 Repo: ${{ github.repository }}
           👤 Author: ${{ github.actor }}
           📝 Commit: ${{ github.event.head_commit.message }}"