name: Daily Changelog

on:
  schedule:
    - cron: '0 15 * * *' # 22:00 WIB
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: log
        run: |
          chmod +x .github/scripts/changelog.generate.sh
          bash .github/scripts/changelog.generate.sh

      - name: Send to Telegram
        run: |
          export TYPE="combined"
          export TEXT="${{ steps.log.outputs.CHANGELOG }}"
          bash .github/scripts/send.telegram.sh