name: Notify Workflow Dev Push

on:
  workflow_dispatch:
  push:
    branches: [main]   # atau branch kamu
    paths-ignore:
     - README.md
     - .github/*.md
     
  workflow_call:
    inputs:
      private_message:
        required: false
        type: string
      channel_message:
        required: false
        type: string
        
    secrets:
      TELEGRAM_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: false
      TELEGRAM_CHANNEL_ID:
        required: false
        
jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PRIVATE_MESSAGE: ${{ inputs.private_message }}
          CHANNEL_MESSAGE: ${{ inputs.channel_message }}
          
        run: |
          # 💜 Kirim ke pribadi (kalau ada)
          if [ ! -z "$PRIVATE_MESSAGE" ]; then
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            --data-urlencode "text=$PRIVATE_MESSAGE"
          fi

          # 📢 Kirim ke channel (kalau ada)
          if [ ! -z "$CHANNEL_MESSAGE" ]; then
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHANNEL_ID \
            --data-urlencode "text=$CHANNEL_MESSAGE"
          fi