name: Notify Commit

on:
  push:
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.parse.outputs.type }}
      detail: ${{ steps.parse.outputs.detail }}
      reaction: ${{ steps.parse.outputs.reaction }}
    
    steps:
      - name: Parse Commit Message
        id: parse
        run: |
          msg="${{ github.event.head_commit.message }}"
          
          if [[ "$msg" == *":"* ]]; then
            type=$(echo "$msg" | cut -d':' -f1)
            detail=$(echo "$msg" | cut -d':' -f2-)
          else
            type="update"
            detail="$msg"
          fi
          
          if [[ "$type" == feat* ]]; then
            reaction="feat"
          elif [[ "$type" == fix* ]]; then
            reaction="fix"
          elif [[ "$type" == refactor* ]]; then
            reaction="refactor"
          elif [[ "$type" == chore* ]]; then
            reaction="chore"
          elif [[ "$type" == docs* ]]; then
            reaction="docs"
          elif [[ "$type" == style* ]]; then
            reaction="style"
          elif [[ "$type" == test* ]]; then
            reaction="test"
          else
            reaction="✨ kamu tetap jalan hari ini... semangat ya farid"
          fi
          
          echo "type=$type" >> $GITHUB_OUTPUT
          echo "detail=$detail" >> $GITHUB_OUTPUT
          echo "reaction=$reaction" >> $GITHUB_OUTPUT
          
  notify:
   needs: prepare
   uses: fridfn/workflow-development/.github/workflows/git.commit.message.yml@main

   with:
     private_message: |
       📦 Repo: ${{ github.repository }}
       👤 Author: ${{ github.actor }}
       📝 Commit: ${{ github.event.head_commit.message }}

     channel_message: |
       # Commit Update
       
       ${{ needs.prepare.outputs.reaction }}
       
       👤 Author  : ${{ github.actor }}
       🌿 Branch  : ${{ github.ref_name }}
       📦 Repo     : ${{ github.repository }}
       
       📝 Type    : ${{ needs.prepare.outputs.type }}
       📑 Info     : ${{ needs.prepare.outputs.detail }}
       
       🔗 Lihat Repo  
       https://github.com/${{ github.repository }}
       
       🔗 Detail Commit  
       https://github.com/${{ github.repository }}/commit/${{ github.sha }}
       ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ
       
   secrets:
     TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
     TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}